@entryPoint = http://localhost:4100

#__________________HOME PAGE
GET {{entryPoint}}

###
#__________________USERS
GET {{entryPoint}}/users

###
#__________________Find one
GET {{entryPoint}}/users/16

###
#__________________Create user
POST {{entryPoint}}/users
Content-type: application/json

{
    "username": "Fredooooo",
    "email": "f@fa.com",
    "password":  "123456",
    "passwordConfirm": "123456",
    "role_id": 2
}

###
#__________________Find one
DELETE {{entryPoint}}/users/20